### ISSUE TITLE
SDK not able to download vector files

### ISSUE THREAD

**Issue by chfabbro** [adobe/stock-api-libphp#1]
When calling `License::downloadAssetRequest()`
 
It should return Guzzle/Request. But instead it triggers exception "No redirection done by server" which comes from `HttpClient::doGet()` method.

Examining the code for `src/Client/License.php` it appears the SDK assumes that all downloads are delivered by 302 redirect, and throws an exception if this doesn't occur. But this is a false assumption, because some files such as vectors are delivered directly with a 200 response.

**Comment by dlemstra** [comment]
Took a quick peek at the code and it looks like this is already resolved? And I am also wondering how a non adobe employee can access `astock/phpcs-psr2-stock` to get the development environment working localy?

**Comment by chfabbro** [comment]
Hi @dlemstra--good point. I did fix this some time ago but did not update the issue. It was updated with this commit: https://github.com/adobe/stock-api-libphp/commit/b74ce5fe79298a62869bedcfc209e4c854f34ffe#diff-d2252580a94038edfd841cab35cabd14

For your second question, that was a mistake. The folder was synced, but Git was ignoring the files because it was a submodule. I have corrected that and you can now pull them down:
https://github.com/adobe/stock-api-libphp/tree/master/libs/phpcs-psr2-stock 

We decided to add them as a sub-repo rather than make the rules public on their own, since they are only referenced in this one repository.
