### ISSUE TITLE
Error in astock/phpcs-psr2-stock  during installation 

### ISSUE THREAD

**Issue by usmaniqbalse** [adobe/stock-api-libphp#4]
Hello, 

I am facing below error after running composer install. 

- Installing astock/phpcs-psr2-stock (v1.5)
    Cloning 8b90e8eab977201120e1f8506e50982b6c939c5b

                                                                               
  [RuntimeException]                                                           
  Failed to execute git clone --no-checkout 'git@git.corp.adobe.com:AdobeStoc  
  k/phpcs-psr2-stock.git' '/var/www/adobe-stock/stock-api-libphp/vendor/astoc  
  k/phpcs-psr2-stock' && cd '/var/www/adobe-stock/stock-api-libphp/vendor/ast  
  ock/phpcs-psr2-stock' && git remote add composer 'git@git.corp.adobe.com:Ad  
  obeStock/phpcs-psr2-stock.git' && git fetch composer                         
  Cloning into '/var/www/adobe-stock/stock-api-libphp/vendor/astock/phpcs-psr  
  2-stock'...                                                                  
  ssh: connect to host git.corp.adobe.com port 22: No route to host            
  fatal: Could not read from remote repository.                                
  Please make sure you have the correct access rights                          
  and the repository exists.                                                   
                                      

https://prnt.sc/k7ez3f

I am waiting for solution.

Thanks & Regards,
Usman

**Comment by irfan-muhammad** [comment]
I am facing the same composer install error.

 Installing astock/phpcs-psr2-stock (v1.5): Cloning 8b90e8eab9

                                                                                                                                                                                                                                                                               
  [RuntimeException]                                                                                                                                                                                                                                                           
  Failed to execute git clone --no-checkout "git@git.corp.adobe.com:AdobeStock/p                                                                                                                                                                                               hpcs-psr2-stock.git" "
  \stock-api-libphp\vendor\astock\phpcs-psr2-stock" && cd /D "'\st                                                                                                                                                                                               ock-api-libphp\vendor\astock\phpcs-ps
  r2-stock" && git remote add composer "git@git.corp.adobe.com:AdobeStock/phpcs-                                                                                                                                                                                               psr2-stock.git" && git fetch composer
                                                                                                                                                                                                                                                                               
  Cloning into '\stock-api-libphp\vendor\astock\phpcs-psr2-stock'                                                                                                                                                                                               ...
  ssh: connect to host git.corp.adobe.com port 22: Connection timed out                                                                                                                                                                                                        
  fatal: Could not read from remote repository.                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                               
  Please make sure you have the correct access rights                                                                                                                                                                                                                          
  and the repository exists.

**Comment by chfabbro** [comment]
Hi @usmaniqbalse and @irfan-muhammad: That should now be fixed. I removed the lint action from composer.json.

**Comment by abulut** [comment]
Hello, I have the same composer install error.
composer install:
 [RuntimeException]
  Failed to execute git clone --no-checkout "git@git.corp.adobe.com:AdobeStock/phpcs-psr2-stock.git"
   "C:\stock_api\vendor\astock\phpcs-psr2-stock" && cd /D "C:\stock_api\vendor\astock\phpcs-psr2-sto
  ck" && git remote add composer "git@git.corp.adobe.com:AdobeStock/phpcs-psr2-stock.git" && git fet
  ch composer

  Cloning into 'C:\stock_api\vendor\astock\phpcs-psr2-stock'...
  ssh: connect to host git.corp.adobe.com port 22: Connection timed out
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.

composer update:
 Problem 1
    - The requested PHP extension ext-imagick * is missing from your system. Install or enable PHP's imagick extension.
  Problem 2
    - The requested package astock/phpcs-psr2-stock could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by chfabbro** [comment]
Hi @abulut, did you try installing using `composer install --no-dev` ? You only need the astock/phpcs-psr2-stock library if you plan to make changes to the SDK itself. Do you plan to do development work on the SDK, or do you only want to use the SDK?

Also, you will need to separately install ext-imagick. Per the instructions:
3. The SDK requires [ImageMagick](https://www.imagemagick.org/script/index.php) be installed on your system, and you will need the ImageMagick PHP extension as well. Once installed, this command should print a "1," assuming you have added PHP to your global PATH:
         `php -r "print(class_exists('imagick'));"`
* On a Mac, you can install this with homebrew using following commands:
* Use `brew search imagick` to get the list of available imagick extensions.
* From the above list, pick latest imagick version and run `brew install homebrew/php/<php-version>-imagick`
            ex: `brew install homebrew/php/php71-imagick`.

* On Windows, Refer to this [article](https://mlocati.github.io/articles/php-windows-imagick.html) or you can use [curl](http://www.queryadmin.com/1556/install-composer-curl/) for the same.

* If ImageMagick is not installed, then it will only affect the similarity (visual) search method of uploading an image. If you don't need this functionality, then you don't need to install it, but you will get warnings from Composer.

**Comment by abulut** [comment]
Hi @chfabbro, for first time i want to use the sdk to get Images for our configurator development. I dont need the ImageMagick search methods of uploads. i tryed to install the composer install of both types. i will try to install astock api with new changes, i hope that will be work now =)
